# -*- mode: ruby -*-

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = "ngi_stats"

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/vivid64"

  # Run the bootstrap.sh script
  config.vm.provision "shell",
    path: "bootstrap.sh",
    privileged: false

  # docker tornado
  config.vm.network "forwarded_port", guest: 8888, host: 8888

  
  config.vm.provider "virtualbox" do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "1"]
  end
end
