# -*- mode: ruby -*-

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.provider "docker" do |d|
        d.build_dir = "."
        d.ports = ["8888:8888"]
        d.remains_running = true
        d.name = "ngi_stats"
        d.env = {"CHARON_BASE_URL" => ENV["CHARON_BASE_URL"], "CHARON_API_TOKEN" => ENV["CHARON_API_TOKEN"]}
        d.vagrant_vagrantfile = "ProxyVM_Vagrantfile"
    end

end
